const WALL: [u128; 16] = [
    0xececebebececebececececebebececeb,
    0xededecebefefeeefefefefeeedeeedec,
    0xededececefefefefeeeeeeeeedededec,
    0xedececebefefefeeeeededededededec,
    0xececebebeeedededededededededeceb,
    0xebebebececececebebececebecebebeb,
    0xefefeeefeeeeeeedebececececececec,
    0xefefeeefeeeeededecedecececececec,
    0xeeeeeeededededececececececececeb,
    0xebececebececececececececebebebeb,
    0xececececebeeefefeeefefefeeededec,
    0xebecececebeeeeeeeeeeeeeeedededec,
    0xebececebebededededededededececec,
    0xebebebebecececebececebebececebeb,
    0xedededededededececedececebededed,
    0xedededededededecededececebededed,
];
