[package]
name = "xeno"
version = "0.1.0"
edition = "2024"

[dependencies]
vizir = { path = "./vizir" }

[build-dependencies]
bmp = "0.5.0"
rgb2ansi256 = "0.1.1"

[workspace]
members = ["vizir"]

[profile.dev]
opt-level = 3
debug = true
strip = "none"
lto = true
panic = "abort"

